### ISSUE TITLE
example-plugin

### ISSUE THREAD

**Issue by strukturart** [rasteiner/oh-hi-mark#2]
Thank you for the plugin!

https://github.com/rasteiner/oh-hi-mark#example-plugin
in which folder do I have to save the files of your example?

**Comment by rasteiner** [comment]
Those would go into a folder in `site/plugins`; like `site/plugins/strukturart/index.php`, etc... 

Since the release of this experiment, [Johann Schopplich's plugin](https://github.com/johannschopplich/kirby-writer-marks) was refactored a bit and does no longer require patching Kirby core (which was the whole point of this repository), so If this one doesn't turn out to work, you might have a look at that one which seems to be better maintained.
